import { type SubscriberConfig, type SubscriberArgs } from "@medusajs/framework"
import { IOrderModuleService } from "@medusajs/types"
import { Modules } from "@medusajs/utils"
import { createOrderFulfillmentWorkflow } from "@medusajs/core-flows"

export default async function autoFulfillOrderHandler({
  event: { data },
  container,
}: SubscriberArgs<{ id: string }>) {
  console.log(`[AutoFulfillSubscriber] Attempting automatic Shiprocket fulfillment for Order: ${data.id}`)
  
  if (process.env.SHIPROCKET_ENV !== "production") {
    console.log(`[AutoFulfillSubscriber] Skipped: SHIPROCKET_ENV is not 'production'`)
    return
  }
  
  const orderModuleService: IOrderModuleService = container.resolve(Modules.ORDER)
  
  const order = await orderModuleService.retrieveOrder(data.id, {
    relations: ["items.item", "shipping_methods", "shipping_address"]
  })

  // We check if it's already fulfilled
  if ((order as any).fulfillment_status === "fulfilled") {
    return
  }

  // Get items to fulfill (all unfulfilled items)
  const itemsToFulfill = order.items?.map(item => ({
    id: item.id,
    quantity: item.quantity,
  }))

  if (!itemsToFulfill || itemsToFulfill.length === 0) {
    return
  }

  try {
    const { result } = await createOrderFulfillmentWorkflow(container).run({
      input: {
        order_id: order.id,
        items: itemsToFulfill,
        labels: [], // Labels are generated by our fulfillment provider later
      }
    })
    console.log(`[AutoFulfillSubscriber] Successfully created fulfillment for Order: ${data.id}`)
  } catch (error: any) {
    console.error(`[AutoFulfillSubscriber] Failed to auto-fulfill order ${data.id}:`, error.message)
  }
}

export const config: SubscriberConfig = {
  event: "order.placed",
}
